export { default as NewsSmallBlock } from './NewsSmallBlock/NewsSMallBlock';
export type { NewsSmallBlockProps } from './NewsSmallBlock/NewsSMallBlock';
export { default as NewsletterBlock } from './NewsletterBlock/NewsletterBlock';
export type { NewsletterBlockProps } from './NewsletterBlock/NewsletterBlock';
export { default as PartnersBlock } from './PartnersBlock/PartnersBlock';
export type { PartnersBlockProps } from './PartnersBlock/PartnersBlock';
export { default as ResultsCard } from './ResultsCard/ResultsCard';
export type { ResultsCardProps } from './ResultsCard/ResultsCard';
export { default as TalksBlock } from './TalksBlock/TalksBlock';
export type { TalksBlockProps } from './TalksBlock/TalksBlock';
